name: davbot_v3a
description: DAVBOT V3A+ - DAV ASISTENMU
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.3.0
  firebase_auth: ^5.3.0
  google_sign_in: ^6.2.1
  google_mobile_ads: ^5.1.0

flutter:
  uses-material-design: true
